name:                euler
version:             0.1.0.0

dependencies:
- base >= 4.10 && < 5

library:
  source-dirs: src

executables:
  simple-library-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - euler
    - file-embed
    - bytestring

tests:
  simple-library-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - euler
    - file-embed
